jbergstroem/mariadb-alpine

README.md, run.sh
This allows you to pass dumps or scripts as part of your database initialization phase.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/5
=> init: implement `docker-entrypoint-initdb.d` support

.github/workflows/build.yml, .github/workflows/test.yml, Dockerfile, README.md, bin/build-image.sh, run.sh, test/01-sanity_check.bats, test/02-innodb.bats, test/03-configuration.bats, test/04-import.bats, test/test_helper.bash
This introduces a test suite using with [`bats`](https://github.com/bats-core/bats-core). There are still lots of things to do, but they can probably be fixed in separate work.
- Add test suite to CI
- Refactor how we invoke the client
- Move cleaning up to setup/teardown style
- Dig into how we run them in parallel; avoid the `sleep` as part of waiting for server to come up.
=> Add a test suite

test/02-innodb.bats, test/03-configuration.bats, test/04-import.bats, test/test_helper.bash
Extract how we call the client into a helper. Also, since `run.sh` branches
for database vs database/user/password, a test is added to reflect this.
Finally, remove `get_ip` since we only call it from the client.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/21
=> test: refactor client

.github/workflows/lint.yml, run.sh
Use [`shellcheck`][1] to verify shell scripts.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/8
[1]: https://www.shellcheck.net/
=> ci: add shell script checks

.dockerignore, .github/workflows/lint.yml, Dockerfile, clean.sh
Significant changes to how we build (clean) the final image; we keep a whitelist instead of selectively removing things. This is moved into a separate script to keep error handling cleaner.
Finally, add [`hadolint`](https://github.com/hadolint/hadolint/) to verify that our Dockerfile is in shape.
The resulting image shrank by about 10%
| Repository | Tag | Image ID | Created | Size |
|:--|:--|:--|:--|:--|
| jbergstroem/mariadb-alpine | `latest` | `b8ebaf0bb7ac` | 10 minutes ago | 38.5MB |
| jbergstroem/mariadb-alpine | `f7e985e` | `7f924e8b227c` | 9 hours ago | 42.2MB |
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/7
Closes: https://github.com/jbergstroem/mariadb-alpine/pull/9
=> Refactor dockerfile

test/02-innodb.bats
Previous versions of MariaDB broke in certain scenarios when using docker, aufs or other mounted drives with Mariadb `10.2.x` and likely also some versions of `10.3.x`.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/1
=> test: check starting InnoDB without a volume

my.cnf
Apply moderate constraint to some of the biggest memory allocations. If you care about performance, you would want to mount your own `my.cnf` instead of using the default anyway.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/18
=> my.cnf: shrink some default memory settings

README.md
..also, minor adjustments; absolute path for the logo to hopefully "automatically" start working on docker hub.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/31
=> README: Re-add CTRL+C

.dockerignore, Dockerfile, clean.sh, resolveip.sh
This shaves off additional size (~9%) from the image. Also, reorder a few things in `Dockerfile` to use caching more efficiently in a developer environment.
| Repository | Commit | Size |
|:--|:--|:--|
| jbergstroem/mariadb-alpine | 13521c1 | 35.1MB |
| jbergstroem/mariadb-alpine | a7a9cdb | 38.5MB |
=> docker: replace `resolveip` with polyfill

.github/workflows/lint.yml, README.md, run.sh, test/03-configuration.bats, test/fixtures/user-my.cnf
You can now provide a custom config file by mounting it into `/etc/my.cnf.d/`.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/34
=> docker: support a custom config file

test/03-configuration.bats
Instead of making an assumption about a row count, we now check that the config setting actually returns what we expect.
=> test/03-import: check return value for innodb

.editorconfig, .github/workflows/lint.yml, .github/workflows/test.yml, README.md
Prettier is a nice way to argue less about semantics. The idea is to pave the way for a `doc` folder, but it also caught irregularities in YAML files.
Refs: https://github.com/jbergstroem/mariadb-alpine/issues/39
=> ci: lint repository with `prettier`

README.md, run.sh, test/03-configuration.bats
When creating a database you can pass these environment variables to control what charset and potentially collation you'd like to use. If you don't provide a charset, `utf8` will be used.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/33
=> Support `MYSQL_CHARSET` and `MYSQL_COLLATION`

.github/workflows/test.yml, Dockerfile, sh/run-tests.bash, test/02-innodb.bats, test/03-configuration.bats, test/04-import.bats, test/test_helper.bash
Introduce running tests in parallel and improve running time while avoiding the default sleep period by tailing logs for ready state.
There is a slight discrepancy between `docker logs` and network being ready, but its small enough in our case to not really matter.
Edit: this cuts about 60% running time on my laptop with 4 cores.
=> Parallel tests

sh/run.sh
This catches use cases where the volume has been tampered with between runs leading to next startup failing.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/54
=> fix: ensure directory ownership on startup

.github/dependabot.yml
In b3c35bc I incorrectly introduced an attribute that was referring to an older version of dependabot.
=> fix: rename dependabot config attribute

Dockerfile, sh/run.sh, test/01-sanity_check.bats, test/04-import.bats, test/fixtures/user-my.cnf
- use `mariadbd` binaries instead of `mysqld` symlinks
- delete symlinks for mysql and mysqld
=> refactor: use mariadb binaries instead of mysql

sh/run-tests.bash
Newer versions of macos seems to lack `nproc` (at least for me), so switch to using `sysctl` instead.
Edit: also, add `DEBUG` as a option to running tests.
=> fix: use sysctl to find cpu cores on macos

test/03-configuration.bats
Note: only applies if InnoDB is disabled.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/108
Refs: https://github.com/jbergstroem/mariadb-alpine/pull/107
=> feat: add test to verify that Aria is default database

Dockerfile, README.md
`ca-certificates` bundles certificates into `/etc/ssl/certs/ca-certificates.crt`
so there's no need for the originals to stay around.
Shaves about `300kb` from image size
=> chore: remove original ca certs

.dockerignore, Dockerfile, sh/my_print_defaults.sh
`my_print_defaults` traverses your configs and returns a commandline representation of options for certain sections; most importantly `mariadb`. This scripts accomplishes the same. It is not without risk, but should be harm free for most - if not everyone. Lets see.
Using `docker save | gzip` (docker uses higher compression settings):
| Version | Size (bytes) | Savings |
| - | - | - |
| 17c5fb6 (master) | 13,242,045 | |
| c01bc7c (this PR) | 12,432,490 | **7.1%** |
=> feat: shin `my_print_defaults`

.github/workflows/lint-shellcheck.yml, README.md, sh/build-image.sh, sh/run-tests.bash, test/01-sanity_check.bats, test/02-innodb.bats, test/03-configuration.bats, test/04-import.bats, test/innodb.sh, test/test_helper.bash
This way we don't have to invoke shellcheck twice.
=> chore: specify parser for all shellscripts

.github/dependabot.yml, .github/renovate.json, .github/workflows/lint.yml, Dockerfile
Benefits:
- grouped updates
- opportunity to update variables in github actions
- track alpine updates for mariadb
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/43
=> feat: replace dependabot with renovate

.github/matcher-actionlint.json, .github/workflows/lint.yml
Switch from the deprecated `::set-output` to a problem matcher.
=> chore: refactor actionlint output

.github/renovate.json, .github/workflows/test.yml
1. Skip annotation and just define attributes in config instead
2. Monitor actionlint
3. Monitor bash_unit
=> feat: improve renovatebot dependency matcher.

.github/renovate.json
By reintroducing `v` as part of the version, the comparison becomes valid.
=> chore: fix version annotation

.github/renovate.json, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, Dockerfile, sh/build-image.sh
The logic is as follows:
1. Extract mariadb version from apk
2. Build and test container on amd64
3. Push to docker hub and github
Options:
With this workflow, mariadb-alpine now supports 7 architectures:
- linux/amd64
- linux/arm/v6
- linux/arm/v7
- linux/arm64
- linux/386
- linux/s390x
- linux/ppc64le
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/29
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/17
=> feat: create a manual release workflow

.github/renovate.json, .github/workflows/lint.yml
Fixes an issue where `v` was handled inconsistently as part of updating the version string.
Refs: https://github.com/jbergstroem/mariadb-alpine/pull/165
=> fix: exclude `v` from versioning

.github/workflows/lint.yml, test/basic.sh, test/config.sh, test/import.sh, test/innodb.sh
Minor nit to make shellcheck happy, the file was incorrectly referenced. It is also assumed that shellcheck is invoked from the root of the directory.
=> fix: correct reference for helper file in tests

.github/renovate.json
Newer default templates in renovatebot's title uses `prettyVersion` which should cover what I want to achieve with titles.
Refs: https://github.com/renovatebot/renovate/issues/13299#issuecomment-1200899853
=> fix: use `prettyVersion` for printing version

.github/renovate.json
Some matchManagers has rules that overrides any global default set. These are overridable with packageRules.
Refs: https://github.com/renovatebot/renovate/issues/18828
=> fix: override matchManager default

Dockerfile
Also, bump to Alpine Linux 3.17. The size increase (~1.5Mb uncompressed) unfortunately comes from this layer.
---
```
-----Size-----
$ container-diff diff daemon://jbergstroem/mariadb-alpine: c80632a daemon://jbergstroem/mariadb-alpine:latest
Image size difference between jbergstroem/mariadb-alpine:c80632a and jbergstroem/mariadb-alpine:latest:
SIZE1        SIZE2
36M          33.6M
$ container-diff diff daemon://jbergstroem/mariadb-alpine:c80632a daemon://jbergstroem/mariadb-alpine:latest --type=file
These entries have been added to jbergstroem/mariadb-alpine:c80632a:
FILE                                   SIZE
/etc/terminfo/k/kitty                  3.3K
/lib/libcrypto.so.1.1                  2.5M
/lib/libssl.so.1.1                     511.4K
/lib/libz.so.1.2.12                    97.9K …
```
=> feat: mariadb 10.6.11

Dockerfile, README.md, docs/usage.md, sh/run.sh, test/_helper.bash
Simplifies tests, usage and loading fixtures at the expense of ~2Mb uncompressed disk space.
Usage:
```console
$ docker run -it --entrypoint mariadb jbergstroem/mariadb-alpine
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
```
Closes: https://github.com/jbergstroem/mariadb-alpine/discussions/140
=> feat: bundle a mariadb client

.github/renovate.json
shfmt passes extra options to curl which makes renovate not match it.
=> fix: match optional output in renovate match

.github/renovate.json
This way, renovate should properly bump the dependency.
=> fix: move "v" outside bash_unit versioning match

docs/configuration.md, docs/usage.md
This seems to be more widely supported in syntax highlighters. Tested a few plugins in VSCode and others; `console` is not picked up.
=> chore(docs): switch code syntax from console to shell

Dockerfile
With Alpine 3.18 we also get the 10.11.x series of MariaDB.
Since `mariadb-client` now requires perl due to some bundled scripts we just remove all installed files by said package.
Closes: https://github.com/jbergstroem/mariadb-alpine/pull/234
=> feat: mariadb 10.11
