.kodiak.toml
[Kodiak][kodiak] allows us to keep PRs up to date if the parent branch is rebased. Its the little things that count.
(it also allows us to merge via label which may come in use later)
[kodiak]: https://kodiakhq.com/
=> feat: automate rebase workflow in PRs

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml
I wrote my own the other day, it should be both faster and provide more options and more up to date version of hadolint.
=> ci: switch to another hadolint action

.github/dependabot.yml
Rename label to follow how other labels are named.
=> ci: rename dependabot label

README.md
Fixes: #72 
- Add more Docker images
- Add port example
=> Fix #72 - Add more Docker images and add port example

.github/workflows/lint.yml
Fail CI if any errors, warnings or info comes out of hadolint.
=> ci: fail any hadolint output

Dockerfile
We previously called `tail` on output from `apk`. This is a remnant from an older script that handled output differently.
This means we now remove more files that shouldn't be part of the distribution.
=> dockerfile: optimize cleanup

Dockerfile, my.cnf, sh/run.sh
Hi @jbergstroem 
First, I'd like to thank you for your work. I use your docker image for my web.
I've updated it to the most recent version of Mariadb and Alpine. 
FYI "/usr/bin/mariadb*" files are binaries and "/usr/bin/mysql*" files are symlinks so I've included them as well.
=> Updated mariadb to 10.6.4-r2 and alpine to 3.15

Dockerfile
- Related to https://github.com/jbergstroem/mariadb-alpine/pull/110
=> Update HEALTHCHECK from mysqld to mariadbd

sh/run.sh
Its an unnecessary optimization - some users have reported issues that may be related but I haven't been able to reproduce.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/62
=> fix: remove `--skip-networking` from sql importer daemon

.github/renovate.json
Copy paste blunder from documentation; didn't notice the regex search at the end.
=> fix: change Dockerfile annotate match

.github/matcher-shellcheck.json, .github/workflows/lint.yml
This will annotate issues in PRs.
=> feat: add a problem matcher for shellcheck

.github/renovate.json
=> chore: slim the renovate config

.github/renovate.json, .github/workflows/lint.yml, .github/workflows/test.yml
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/162
=> feat: improve renovatebot matchers

docs/usage.md
An example on how to import tzdata to your mariadb container.
=> chore(doc): import tzdata

.github/workflows/release.yml, README.md, docs/development.md
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/182
=> chore(doc): add developer documentation

docs/benchmarks.md, sh/generate-benchmark.sh
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/187
=> feat: sort benchmark by size

.github/workflows/dockerhub.yml, .gitignore, README.md, sh/generate-dockerhub-readme.sh
If README.md changes (and lands to main), update Docker Hub.
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/169
=> feat: update Docker Hub metadata

docs/development.md
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/185
=> chore(doc): releases with `gh-cli`

docs/benchmarks.md, sh/generate-benchmark.sh
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/188
=> feat: show daemon version in benchmark

Dockerfile
Also, update Alpine to 3.18.4
Closes: https://github.com/jbergstroem/mariadb-alpine/pull/256
=> chore(deps): update mariadb to 10.11.5

.github/workflows/dockerhub.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/todo.yml
This probably needs to be coupled with a renovate config. Will look at this later.
Closes: https://github.com/jbergstroem/mariadb-alpine/pull/257
=> fix(deps): don't pin github action to sha

.github/renovate.json
Fixes: https://github.com/jbergstroem/mariadb-alpine/issues/239
=> fix: bump alpine repo for renovate changes

.github/renovate.json
=> chore(deps): don't split out major bumps
